image: debian

before_script:
  - apt-get update -qq
  - apt-get install -y -qq build-essential autoconf autoconf-archive automake libtool m4 pkg-config

stages:
  - test

test-job:
  stage: test
  script:
    - autoreconf --install
    - mkdir build
    - cd build
    - ../configure
    - make
    - whoami
    - id
    - cat /etc/os-release
    - make check
